### ISSUE TITLE
Working Demo?

### ISSUE THREAD

**Issue by atkinsonm** [bdesilva/terraform-ui#1]
Do you have a working demo of this? I'd love to see it. I've been working with Terraform and Ansible and the one thing I think Ansible has over Terraform is a nice GUI with Ansible Tower. I think a GUI that could show the current state of your infrastructure or provide a non-CLI interface to run jobs would be attractive to a lot of people.

**Comment by bdesilva** [comment]
Hi, not yet, I had originally started doing this in AngularJS after making all the architectural plans, however I am now starting to rewrite this in ReactJS so I should have something out in a couple of weeks that will allow the user to navigate through a UI to build out their infrastructure as well as show its state. Working on a good solution for running the jobs as well, so stay tuned :)

**Comment by atkinsonm** [comment]
Very cool, I'll watch this repo for future updates!
